### ISSUE TITLE
wording

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/shoutkey#1]
I have never hear the term "escape" in regards to a website. The "CREATING A SHOUTKEY" paragraph did not make sense to me until I had someone explain it. You may consider rewriting and more simply explaining what escaping a website is.  Also, should it be "uri escaped uri" in the first sentence? I'm still not sure I understand.

Maybe:  "Here is a url '<blah>'.  Here is what that url looks like as an escaped uri, '<%#&$blah%*^#>'."  And then why this exists.

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by AnnJohn** [comment]
Lab to be deprecated, so closing issue.
