### ISSUE TITLE
nokogiri passing when shouldnt

### ISSUE THREAD

**Issue by EJLarcs** [learn-co-curriculum/shoutkey#2]
Test should confirm you use nokogiri in the shoutkey - i was able to pass without doing so (simply assigning a link and returning it)

**Comment by AnnJohn** [comment]
@EJLarcs Can you give some more specifics on the issue?
What were you expecting to see, and in which file and which line(s)? A screenshot would be extra helpful.
What were you expecting to happen and what did happen?
Can you be more specific about a suggested solution. Feel free to include it in your comments. 

Please follow up by 8/21

**Comment by AnnJohn** [comment]
@SophieDeBenedetto due by 8/28

**Comment by AnnJohn** [comment]
Lab to be deprecated, so closing issue.
