### ISSUE TITLE
not sure if it's a valid URL or NOT

### ISSUE THREAD

**Issue by alouanemed** [learn-co-curriculum/shoutkey#3]
The given URL should be a correct URL not a random string, to make it a short one !

**Comment by AnnJohn** [comment]
@alouanemed  Can you give some more specifics on the issue?
What were you expecting to see, and in which file and which line(s)? A screenshot would be extra helpful.
What were you expecting to happen and what did happen?
Can you be more specific about a suggested solution. Feel free to include it in your comments. 

Please respond by 8/21; thanks

**Comment by AnnJohn** [comment]
@SophieDeBenedetto  due 8/28

**Comment by alouanemed** [comment]
Hey @AnnJohn 

the input should be a valid URL not a random string e.g : in the picture below the form accepted "qsdq" as URL : 
![screenshot from 2015-08-20 20 16 01](https://cloud.githubusercontent.com/assets/7117097/9393166/6bd09f1e-4778-11e5-9842-1bc240fcb9ee.png)

**Comment by AnnJohn** [comment]
@alouanemed Great; thanks for the clarification!

**Comment by alouanemed** [comment]
@AnnJohn ^^

**Comment by AnnJohn** [comment]
Lab to be deprecated, so closing issue.
